export const SET_ACTIVE_STATIC_BAR = "ACTIVE_STATIC_BAR";
export const SET_LOGIN_PAGE_RELOAD = "LOGIN_PAGE_RELOAD";
export const SET_USER_PROFILE_DATA = "SET_USER_PROFILE_DATA";
export const SET_MOBILE_BAR_DATA = "SET_MOBILE_BAR_DATA";
export const SET_MDS_DATA = "SET_MDS_DATA";
export const SET_DDS_DATA = "SET_DDS_DATA";
export const SET_SDS_DATA = "SET_SDS_DATA";


export const SET_ITEM_ON_SALE_DATA = "SET_ITEM_ON_SALE_DATA";
export const SET_MIDDLE_LOADER = "SET_MIDDLE_LOADER";
export const SET_STEP = "SET_STEP";
export const SET_PRICE_VALUE = "SET_PRICE_VALUE";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const SET_RECOMMENDED_PRICE = "SET_RECOMMENDED_PRICE";
export const SET_UNREAD_NOTI_LENGTH = "SET_UNREAD_NOTI_LENGTH";
export const SET_AUTH_MODAL_SHOW = "SET_AUTH_MODAL_SHOW";
export const SET_AUTH_MODAL_HIDE = "SET_AUTH_MODAL_HIDE";
export const SET_CARD_DETAILS_ACTIVE = "SET_CARD_DETAILS_ACTIVE";
export const SET_CARD_DETAILS_DEACTIVE = "SET_CARD_DETAILS_DEACTIVE";
export const GET_ALL_SKIN = "GET_ALL_SKIN";
export const GET_ALL_SKIN_FALSE = "GET_ALL_SKIN_FALSE";
export const AUTH_MODAL_OPEN = "AUTH_MODAL_OPEN";
export const AUTH_MODAL_CLOSE = "AUTH_MODAL_CLOSE";
